name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # The Go version to download (if necessary) and use.

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      # - name: Build
      #   run: make build

      - name: Test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Run
    #   run: ./myapiclient
    #   env:
    #     SOME_ENV_VARIABLE: some-value
